---
assignees: ["martinohmann"]
body:
  - attributes:
      value: |
        Thanks for taking the time to fill out this bug report 🤗.
        Make sure there aren't any open/closed issues for this topic 😃.
    type: markdown
  - attributes:
      description: >
        Give us a brief description of what happened and what should have
        happened.
      label: Description of the bug
    id: bug-description
    type: textarea
    validations:
      required: true
  - attributes:
      description: Steps to reproduce the behavior.
      label: Steps To Reproduce
    id: steps-to-reproduce
    type: textarea
    validations:
      required: true
  - attributes:
      description: >
        Provide any additional information such as logs, screenshots, likes,
        scenarios in which the bug occurs so that it facilitates resolving the
        issue.
      label: Additional Information
    id: additional-information
    type: textarea
description: File a bug report here.
labels: ["bug"]
name: 🐛Bug Report
title: "[bug]: "
