---
assignees: ["martinohmann"]
body:
  - attributes:
      value: >
        Please make sure this feature request hasn't been already submitted by
        someone by looking through other open/closed issues.
    type: markdown
  - attributes:
      description: >
        Give us a brief description of the feature or enhancement you would
        like.
      label: Description
    id: description
    type: textarea
    validations:
      required: true
  - attributes:
      label: Additional Information
      description: >
        Give us some additional information on the feature request like
        proposed solutions, links, screenshots, etc.
    id: additional-information
    type: textarea
description: Request a new feature or enhancement.
labels: ["enhancement"]
name: ✨Feature Request
title: "[feature]: "
